#!/usr/bin/env python3
"""
Configuration Generator

Generates device configurations based on NetBox data using Jinja2 templates.
Supports multiple vendors: Cisco, Juniper, Arista
"""

from jinja2 import Environment, FileSystemLoader, BaseLoader
from pathlib import Path

# Embedded templates for when template files don't exist
CISCO_IOS_TEMPLATE = """!
! {{ device.name }} Configuration
! Generated by NetBox-EVE-NG Automation
!
hostname {{ device.name }}
!
ip domain-name {{ defaults.domain }}
!
{% if defaults.enable_secret %}
enable secret {{ defaults.enable_secret }}
{% endif %}
!
username {{ defaults.username }} privilege 15 secret {{ defaults.password }}
!
{% for interface in interfaces %}
interface {{ interface.name }}
 description {{ interface.description | default('') }}
{% if interface.ip_address %}
 ip address {{ interface.ip_address | ip_address }} {{ interface.ip_address | netmask }}
{% endif %}
{% if interface.enabled %}
 no shutdown
{% else %}
 shutdown
{% endif %}
!
{% endfor %}
!
{% if defaults.ssh_enabled %}
ip ssh version 2
ip ssh time-out 60
ip ssh authentication-retries 3
!
line vty 0 4
 login local
 transport input ssh
!
crypto key generate rsa modulus 2048
{% endif %}
!
{% if defaults.netconf_enabled %}
netconf-yang
netconf ssh
{% endif %}
!
{% if defaults.ntp_server %}
ntp server {{ defaults.ntp_server }}
{% endif %}
!
ip route 0.0.0.0 0.0.0.0 {{ defaults.gateway | default('192.0.2.1') }}
!
end
"""

JUNIPER_TEMPLATE = """
## {{ device.name }} Configuration
## Generated by NetBox-EVE-NG Automation

system {
    host-name {{ device.name }};
    domain-name {{ defaults.domain }};
{% if defaults.password_hash %}
    root-authentication {
        encrypted-password "{{ defaults.password_hash }}";
    }
    login {
        user {{ defaults.username }} {
            class super-user;
            authentication {
                encrypted-password "{{ defaults.password_hash }}";
            }
        }
    }
{% else %}
    /* Skipping root/user auth: device_defaults.password_hash not set.
       Junos does not accept plaintext in encrypted-password. Generate a
       hash with: openssl passwd -6 'your-password' */
{% endif %}
    services {
{% if defaults.ssh_enabled %}
        ssh;
{% endif %}
{% if defaults.netconf_enabled %}
        netconf {
            ssh;
        }
{% endif %}
    }
{% if defaults.ntp_server %}
    ntp {
        server {{ defaults.ntp_server }};
    }
{% endif %}
}

interfaces {
{% for interface in interfaces %}
    {{ interface.name | juniper_interface }} {
        description "{{ interface.description | default('') }}";
{% if interface.ip_address %}
        unit 0 {
            family inet {
                address {{ interface.ip_address }};
            }
        }
{% endif %}
    }
{% endfor %}
}

routing-options {
    static {
        route 0.0.0.0/0 next-hop {{ defaults.gateway | default('192.0.2.1') }};
    }
}
"""

ARISTA_TEMPLATE = """
! {{ device.name }} Configuration
! Generated by NetBox-EVE-NG Automation
!
hostname {{ device.name }}
!
ip domain-name {{ defaults.domain }}
!
{% if defaults.enable_secret %}
enable secret {{ defaults.enable_secret }}
{% endif %}
!
username {{ defaults.username }} privilege 15 secret {{ defaults.password }}
!
{% for interface in interfaces %}
interface {{ interface.name }}
   description {{ interface.description | default('') }}
{% if interface.ip_address %}
   ip address {{ interface.ip_address }}
{% endif %}
{% if interface.enabled %}
   no shutdown
{% else %}
   shutdown
{% endif %}
!
{% endfor %}
!
{% if defaults.ssh_enabled %}
management api http-commands
   no shutdown
!
{% endif %}
!
{% if defaults.netconf_enabled %}
management api netconf
   transport ssh default
!
{% endif %}
!
ip route 0.0.0.0/0 {{ defaults.gateway | default('192.0.2.1') }}
!
end
"""


class ConfigGenerator:
    """Generate device configurations from NetBox data."""

    def __init__(self, topology: dict, template_dir: str = "templates"):
        """Initialize the config generator."""
        self.topology = topology
        self.defaults = topology.get("device_defaults", {})
        self.template_dir = Path(template_dir)

        # Set up Jinja2 environment
        self.env = Environment(loader=BaseLoader())

        # Add custom filters
        self.env.filters["ip_address"] = self._filter_ip_address
        self.env.filters["netmask"] = self._filter_netmask
        self.env.filters["juniper_interface"] = self._filter_juniper_interface

    def _filter_ip_address(self, cidr: str) -> str:
        """Extract IP address from CIDR notation."""
        if "/" in cidr:
            return cidr.split("/")[0]
        return cidr

    def _filter_netmask(self, cidr: str) -> str:
        """Convert CIDR prefix to netmask."""
        if "/" not in cidr:
            return "255.255.255.0"

        prefix = int(cidr.split("/")[1])
        mask = (0xffffffff >> (32 - prefix)) << (32 - prefix)
        return f"{(mask >> 24) & 0xff}.{(mask >> 16) & 0xff}.{(mask >> 8) & 0xff}.{mask & 0xff}"

    def _filter_juniper_interface(self, name: str) -> str:
        """Convert interface name to Juniper format."""
        # GigabitEthernet0/0 -> ge-0/0/0
        if name.startswith("GigabitEthernet"):
            parts = name.replace("GigabitEthernet", "").split("/")
            if len(parts) == 2:
                return f"ge-{parts[0]}/0/{parts[1]}"
        return name

    def get_template(self, vendor: str) -> str:
        """Get the appropriate template for a vendor."""
        templates = {
            "cisco": CISCO_IOS_TEMPLATE,
            "juniper": JUNIPER_TEMPLATE,
            "arista": ARISTA_TEMPLATE
        }

        # Try to load from file first
        template_file = self.template_dir / f"{vendor}.j2"
        if template_file.exists():
            return template_file.read_text()

        return templates.get(vendor, CISCO_IOS_TEMPLATE)

    def generate_config(self, device: dict, interfaces: list,
                        vendor: str = "cisco") -> str:
        """Generate configuration for a device."""
        # Determine vendor from device type if not specified
        if not vendor:
            device_type = device.get("device_type", {})
            manufacturer = device_type.get("manufacturer", {})
            vendor = manufacturer.get("slug", "cisco")

        # Prepare interface data
        interface_data = []
        for iface in interfaces:
            iface_info = {
                "name": iface.get("name"),
                "description": iface.get("description", ""),
                "enabled": iface.get("enabled", True),
                "ip_address": None
            }

            # Get IP from topology definition
            for topo_device in self.topology.get("devices", []):
                if topo_device["name"] == device["name"]:
                    for topo_iface in topo_device.get("interfaces", []):
                        if topo_iface["name"] == iface["name"]:
                            iface_info["ip_address"] = topo_iface.get("ip_address")
                            iface_info["description"] = topo_iface.get("description", "")
                            break

            interface_data.append(iface_info)

        # Build a per-render defaults dict so we don't mutate self.defaults
        # across calls.
        mgmt_net = self.topology.get("management_network", {})
        render_defaults = {
            **self.defaults,
            "gateway": self.defaults.get("gateway") or mgmt_net.get("gateway", "192.0.2.1"),
        }

        template_str = self.get_template(vendor)
        template = self.env.from_string(template_str)

        return template.render(
            device=device,
            interfaces=interface_data,
            defaults=render_defaults,
        )

    def generate_all_configs(self, devices: list,
                             interfaces_by_device: dict) -> dict:
        """Generate configurations for all devices."""
        configs = {}

        for device in devices:
            device_name = device["name"]
            device_interfaces = interfaces_by_device.get(device_name, [])

            # Determine vendor
            device_type = device.get("device_type", {})
            manufacturer = device_type.get("manufacturer", {})
            vendor = manufacturer.get("slug", "cisco")

            config = self.generate_config(device, device_interfaces, vendor)
            configs[device_name] = config

        return configs

    def save_config(self, device_name: str, config: str,
                    output_dir: str = "configs"):
        """Save configuration to file."""
        output_path = Path(output_dir)
        output_path.mkdir(exist_ok=True)

        config_file = output_path / f"{device_name}.cfg"
        config_file.write_text(config)

        return str(config_file)